### ISSUE TITLE
Some upgrade info to 0.9.0+, couldn't find any elsewhere

### ISSUE THREAD

**Issue by crumhorn** [apollostack/apollo-angular#264]
I searched high and low for some info on what changed from < v0.9 and why my code wouldn't work after upgrading to the latest versions. I was half expecting one of the apollo blogs to say something but unless I missed it, there's nothing. Especially that one package changed names completely. So for those in the same boat:

Here's package.json now (you may not need -rxjs or -server)

 ```
   (you get rid of "angular2-apollo")
   "apollo-angular": "0.9.1",
    "apollo-client": "0.8.0",
    "apollo-client-rxjs": "0.4.1",
    "apollo-server": "0.3.3",
```

and latest graphql as of this writing (whichever you need):

```
    "graphql": "0.9.0",
    "graphql-tools": "0.9.2",
    "graphql-relay": "0.5.0",
    "graphql-typings": "0.0.1-beta-2",
    "graphql-anywhere": "2.0.0",
```

in system.config.js these mappings were updated to point to the .umd. files:

```
        'apollo-angular': {main: 'build/bundles/apollo.umd.js', defaultExtension: 'js'},
        'apollo-client': {main: 'apollo.umd.js', defaultExtension: 'js'},
        'apollo-client-rxjs': {main: 'build/bundles/apollo-rxjs.umd.js', defaultExtension: 'js'},

```

in my app.module.ts:
```

const networkInterface = createNetworkInterface({uri: 'http://localhost:3000/graphql', opts: { credentials: 'same-origin'}});
const client = new ApolloClient({
    networkInterface: networkInterface
});

// this got added
export function getClient(): ApolloClient {
    return client;
}

@NgModule({
    imports: [
        ApolloModule.withClient(getClient),
        ...
```

And wherever you had an import that said:

`import {Angular2Apollo} from "angular2-apollo";`

Change it to:

`import {Angular2Apollo} from "apollo-angular";`

Hope that helps someone else. 

(Feel free to close this "issue" as it's not an issue, couldn't find where else to post it)

**Comment by kamilkisiela** [comment]
I described my changes in [`CHANGELOG.md`](https://github.com/apollostack/apollo-angular/blob/master/CHANGELOG.md#v090). Yes, it's pretty technical, because you have to look at the code :) 

We changed the name of the package but I think you can still use `angular2-apollo`, I mean it should work but it's deprecated now in favor of `apollo-angular`. And yes, we haven't mentioned about it in anywhere...

We're working on a brand new version that supports multiple client (`ApolloClient`) and also there's going to be a breaking change. There will be no `Angular2Apollo`, just `Apollo`.

About `SystemJS`. Would you mind to create a PR that adds a chapter about SystemSJ configuration to [angular2-docs](https://github.com/apollostack/angular2-docs)

**Comment by kamilkisiela** [comment]
And you can replace `graphql-typings` with `@types/graphql`

**Comment by Urigo** [comment]
thank you @crumhorn !
closing as we moved on to `0.10.0` and everyone who will search for the update will end up here or in the changelog.
